// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwsbAd3qNyC0t5P1ExLrhX6ipvI3pmNjc',
    appId: '1:852975756222:web:e423ba70c2c6ecaccb0fef',
    messagingSenderId: '852975756222',
    projectId: 'namibia-hockey-app-579ac',
    authDomain: 'namibia-hockey-app-579ac.firebaseapp.com',
    storageBucket: 'namibia-hockey-app-579ac.firebasestorage.app',
    measurementId: 'G-SY4XJN3LBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA60aTSynjeTycYacqlctQP25wnumsbVI',
    appId: '1:852975756222:android:8bc9e376e8a0bb03cb0fef',
    messagingSenderId: '852975756222',
    projectId: 'namibia-hockey-app-579ac',
    storageBucket: 'namibia-hockey-app-579ac.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwsbAd3qNyC0t5P1ExLrhX6ipvI3pmNjc',
    appId: '1:852975756222:web:6bf6a6c0634904edcb0fef',
    messagingSenderId: '852975756222',
    projectId: 'namibia-hockey-app-579ac',
    authDomain: 'namibia-hockey-app-579ac.firebaseapp.com',
    storageBucket: 'namibia-hockey-app-579ac.firebasestorage.app',
    measurementId: 'G-PFYFXBMKFT',
  );
}
